### ISSUE TITLE
[FEAT] is there anyway to add REST API for fetching data? 

### ISSUE THREAD

**Issue by hellpirat** [ranimepiracy/index#17]
I think it would be cool to add some REST API to fetch this data from your server for third-party apps.

Maybe also I can help to build some cool frontend with this API :)

**Comment by Yasamato** [comment]
We are currently working on exactly that API, but we have not discussed whether we want it to be available to be used by third-parties.
You have the option to just host this project yourself and change the CORS-setting to your own liking, as this is a FOSS project.

We will have an internal discussion about it as I cannot decide this alone.

You have to understand, that we have concerns about increased traffic and as such increased loads on our own server, which we need to finance ourself. If the loads are drastically increased we have concerns about not being able to fund ourself anymore. This is also the reason we had to add a sponsored section, which we would have really liked to not have to add it, but we made a big minus every month and some mods had to pay it all of their own pockets

**Comment by hellpirat** [comment]
Okie, so now it's a work in progress because I cannot find this API in the source code. Any estimation to add this? Or maybe I can help somehow?

**Comment by Yasamato** [comment]
It is a WIP and currently only in the branch `db-migration` at https://github.com/ranimepiracy/index/blob/db-migration/piracymoe/api.py. We want to migrate fully away from github-pages to the self-hosted docker-image

**Comment by hellpirat** [comment]
Thank you, I will take a look

**Comment by Yasamato** [comment]
Take a look at https://github.com/ranimepiracy/index/blob/master/docs/API.MD, we would appreciate it if you use proper caching and don't abuse our service
