### ISSUE TITLE
Could you add full link of a source in the Export function?

### ISSUE THREAD

**Issue by i2324561w2** [ranimepiracy/index#21]
I was thinking about exporting periodically the list in case the site goes down, and a full link will prevent users from going to scam sites with same name.
(I also considered web.archive, but unfortunately it doesn't work very well on this site)
Also I don't know if it's intended, but it will be exported only what is selected by the columns filter, and one Export-all would be quite awesome!

**Comment by Yasamato** [comment]
We want to create a public API for all the data and will implement a feature for that.

At the moment the export is limited by the 3rd-party lib [tabulator.info](http://tabulator.info/) that we use. Expect the current situation to continue for a longer time.

As a workaround you can dump the json object containing all data with:

1. Open [piracy.moe](https://piracy.moe/) and wait till everythings loaded
2. Open dev console, usually `F12` key
3. Go to the console tab
4. Enter the following code:
```javascript
(function() {
    var a = document.createElement("a");
    var file = new Blob([JSON.stringify(window.rawData)], {type: 'text/plain'});
    a.href = URL.createObjectURL(file);
    a.download = "backup-piracy.moe.json";
    a.click();
})()
```
5. Press `Enter` and save the file

**Comment by Axe090** [comment]
> We want to create a public API for all the data and will implement a feature for that.
> 
> At the moment the export is limited by the 3rd-party lib [tabulator.info](http://tabulator.info/) that we use. Expect the current situation to continue for a longer time.
> 
> As a workaround you can dump the json object containing all data with:
> 
>     1. Open [piracy.moe](https://piracy.moe/) and wait till everythings loaded
> 
>     2. Open dev console, usually `F12` key
> 
>     3. Go to the console tab
> 
>     4. Enter the following code:
> 
> 
> ```js
> (function() {
>     var a = document.createElement("a");
>     var file = new Blob([JSON.stringify(window.rawData)], {type: 'text/plain'});
>     a.href = URL.createObjectURL(file);
>     a.download = "backup-piracy.moe.json";
>     a.click();
> })()
> ```
> 
>     5. Press `Enter` and save the file



> We want to create a public API for all the data and will implement a feature for that.
> 
> At the moment the export is limited by the 3rd-party lib [tabulator.info](http://tabulator.info/) that we use. Expect the current situation to continue for a longer time.
> 
> As a workaround you can dump the json object containing all data with:
> 
>     1. Open [piracy.moe](https://piracy.moe/) and wait till everythings loaded
> 
>     2. Open dev console, usually `F12` key
> 
>     3. Go to the console tab
> 
>     4. Enter the following code:
> 
> 
> ```js
> (function() {
>     var a = document.createElement("a");
>     var file = new Blob([JSON.stringify(window.rawData)], {type: 'text/plain'});
>     a.href = URL.createObjectURL(file);
>     a.download = "backup-piracy.moe.json";
>     a.click();
> })()
> ```
> 
>     5. Press `Enter` and save the file

This does'nt work in the new index, can you please add a similar functionality.

**Comment by Axe090** [comment]
> We want to create a public API for all the data and will implement a feature for that.
> 
> At the moment the export is limited by the 3rd-party lib [tabulator.info](http://tabulator.info/) that we use. Expect the current situation to continue for a longer time.
> 
> As a workaround you can dump the json object containing all data with:
> 
>     1. Open [piracy.moe](https://piracy.moe/) and wait till everythings loaded
> 
>     2. Open dev console, usually `F12` key
> 
>     3. Go to the console tab
> 
>     4. Enter the following code:
> 
> 
> ```js
> (function() {
>     var a = document.createElement("a");
>     var file = new Blob([JSON.stringify(window.rawData)], {type: 'text/plain'});
>     a.href = URL.createObjectURL(file);
>     a.download = "backup-piracy.moe.json";
>     a.click();
> })()
> ```
> 
>     5. Press `Enter` and save the file

This doesn't work in the new index, can you please add a similar functinality.

**Comment by Yasamato** [comment]
I now added an export link at the bottom of the footer on every page. Feel free to use it and backup the data, analyze it or whatever :D

Currently put that behind the "super secure", "anti-bot proof" protection of discord to prevent abuse...

<img width="663" alt="Bildschirmfoto 2022-01-20 um 00 30 22" src="https://user-images.githubusercontent.com/27964795/150234963-8001ee55-f36d-4450-be33-c42c6ce701d0.png">
