### ISSUE TITLE
[BUG] A lot of missing data in the preview page with no ability to sort by features in new index

### ISSUE THREAD

**Issue by rsmyst** [ranimepiracy/index#41]
As title says, for me, no data appears along with the website. lemme get a screenshot.

this is what i see,
![image](https://user-images.githubusercontent.com/30620767/141987696-d350902e-dee8-452a-b7cb-7c4ddb1751e2.png)

Compared to this in old sit.
![image](https://user-images.githubusercontent.com/30620767/141987733-c3216714-43d9-4819-831e-29579e3794da.png)

Where you can quickly glance over the data
did I miss something?

**Comment by Yasamato** [comment]
Yep can confirm the issue...

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is this possible? I have not been able to ascertain how to utilise the new interface.
